version: "2"
services:
    mongodb:
        container_name: mongo
        image: mongo:latest
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"

    mongo-seed:
        build: ./mongo-seed
        links:
            - mongodb
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
    app:
        container_name: pokerank_app
        restart: always
        build: .
        ports:
            - "3001:3001"
        links:
            - mongodb
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017


